### ISSUE TITLE
ValueError: too many values to unpack (expected 2) when multiple double slash is present

### ISSUE THREAD

**Issue by whc2001** [ywaby/keil2sdcc#2]
```
#ifndef __STC15F2K60S2_H_
#define __STC15F2K60S2_H_

/////////////////////////////////////////////////
//注意: STC15W4K32S4系列的芯片,上电后所有与PWM相关的IO口均为
//      高阻态,需将这些口设置为准双向口或强推挽模式方可正常使用
//相关IO: P0.6/P0.7/P1.6/P1.7/P2.1/P2.2
//        P2.3/P2.7/P3.7/P4.2/P4.4/P4.5
/////////////////////////////////////////////////
...
```

```
Traceback (most recent call last):
  File "C:\Users\WHC\Desktop\keil2sdcc\keil2sdcc\__main__ - 副本.py", line 2, in <module>
    C51_2_SDCC(r"D:\PlatformIO_Projects\Test8051\include\STC15F.h", r"./out.h")
  File "C:\Users\WHC\Desktop\keil2sdcc\keil2sdcc\c512sdcc.py", line 39, in __init__
    self.convert_file()
  File "C:\Users\WHC\Desktop\keil2sdcc\keil2sdcc\c512sdcc.py", line 46, in convert_file
    sdcc_lines += self.__convert_line(line)
  File "C:\Users\WHC\Desktop\keil2sdcc\keil2sdcc\c512sdcc.py", line 110, in __convert_line
    indent, statements_words, statements_line_end, comments = self.__parse_line(
  File "C:\Users\WHC\Desktop\keil2sdcc\keil2sdcc\c512sdcc.py", line 87, in __parse_line
    statements_line, comments = c_line.split("//")
ValueError: too many values to unpack (expected 2)
```

Quick and dirty solution: change here

https://github.com/ywaby/keil2sdcc/blob/6cf8b91e31df6ebbadb5f5a5fab093a70ed8dd41/keil2sdcc/c512sdcc.py#L87

to

```
statements_line, comments = c_line[:c_line.find("//")], c_line[c_line.find("//") + 2:]
```

**Comment by ywaby** [comment]
fixed
